default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: yukon519

development:
  <<: *default
  database: db/development.mysql2
  
  # database: db/development.sqlite3

test:
  <<: *default
  database: db/test.mysql2
  
  # database: db/test.sqlite3

production:
  url: <%= ENV['MOTOTROVA_DATABASE_URL'] %>