# config/external_database.yml
default: &default  
  encoding: utf8
  adapter: mysql2
  port: 3306

development:  
  <<: *default
  database: mototrova
  host: here_goes_the_host
  username: mototrova
  password: here_goes_the_passowrd 

test:  
  <<: *default
  host: localhost
  username: change
  password: change
  database: external_db_test

production:
  <<: *default
  host: office.ekiwi.net
  username: mototrova
  password: ENV['EXTERNAL_DB_PASSWORD']
